baseURL = '/'
languageCode = 'es'
title = 'Salva SM'
theme = 'salvasm'

[menu]
[[menu.main]]
  identifier = 'cv'
  name = 'CV'
  url = '/cv/'
  weight = 1
[[menu.main]]
  identifier = 'projects'
  name = 'Proyectos'
  url = '/projects/'
  weight = 2
 [[menu.main]]
  identifier = 'photo'
  name = 'Fotograf√≠a'
  url = '/photo/'
  weight = 3
[[menu.main]]
  identifier = 'contact'
  name = 'Contacto'
  url = '/contact/'
  weight = 4

[[menu.social]]
  identifier = 'gmail'
  name = 'Gmail'
  url = 'mailto:salvador.sanchez.mendez@gmail.com'
  weight = 1
[[menu.social]]
  identifier = 'linkedin'
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/salvasm'
  weight = 2
[[menu.social]]
  identifier = 'instagram'
  name = 'Instagram'
  url = 'https://www.instagram.com/salva_sm'
  weight = 3
[[menu.social]]
  identifier = 'twitter'
  name = 'Twitter'
  url = 'https://www.twitter.com/_salvasm'
  weight = 4
[[menu.social]]
  identifier = '500px'
  name = '500px'
  url = 'https://500px.com/p/salva_sm'
  weight = 5